import pkg from 'mongodb';
const { ObjectId } = pkg;

/**
 * Schema definition for enhanced patient profiles with structured medical data
 * This will be used for the RAG pipeline to store and retrieve patient data
 */

// Patient profile schema
export const PatientProfileSchema = {
  patientId: ObjectId,
  email: String, // Primary link to appointments
  basicInfo: {
    name: String,
    age: Number,
    gender: String,
    contact: String,
    email: String,
    emergencyContact: String,
    bloodGroup: String,
    height: Number,
    weight: Number,
  },
  medicalHistory: {
    allergies: [String],
    chronicConditions: [String],
    pastSurgeries: [{
      procedure: String,
      date: Date,
      notes: String
    }],
    familyHistory: [String]
  },
  visits: [{
    date: Date,
    doctorId: ObjectId,
    appointmentId: ObjectId, // Reference to the original appointment
    chiefComplaints: [String],
    symptoms: [{
      name: String,
      severity: Number, // 1-10 scale
      duration: String,
      notes: String
    }],
    vitalSigns: {
      temperature: Number,
      bloodPressure: String,
      heartRate: Number,
      respiratoryRate: Number,
      oxygenSaturation: Number
    },
    diagnosis: [{
      condition: String,
      icd10Code: String,
      notes: String
    }],
    prescriptions: [{
      medicine: String,
      dosage: String,
      duration: Number,
      instructions: String
    }],
    labTests: [{
      testName: String,
      results: String,
      referenceRange: String,
      isAbnormal: Boolean
    }],
    medicalImages: [{
      type: String, // X-Ray, ECG, MRI, etc.
      imageId: String,
      findings: String,
      recommendation: String
    }],
    meetingUrl: String, // URL for Zoom meeting
    transcriptSummary: String, // Summary of meeting transcript
    followupActions: [{
      text: String, // The action item text
      assignedTo: String, // patient, doctor, etc.
      dueDate: Date, // When this action should be completed
      status: String, // pending, completed, overdue
      priority: String, // low, medium, high
      createdAt: Date, // When this action was created
      source: String // meeting-recording, doctor-input, etc.
    }],
    summaryText: String, // Generated by LLM
    followUpDate: Date
  }],
  aiGeneratedInsights: {
    overallHealth: {
      score: Number, // 0-100
      lastUpdated: Date
    },
    chronicDiseaseRisk: [{
      condition: String,
      risk: Number, // 0-100
      factors: [String]
    }],
    healthTrends: [{
      metric: String,
      trend: String, // improving, stable, declining
      data: [Number],
      dates: [Date]
    }],
    recommendedActions: [{
      action: String,
      priority: Number, // 1-5
      reasoning: String
    }]
  },
  // Embeddings for RAG system
  vectorData: {
    profileEmbedding: [Number],
    visitEmbeddings: [{
      visitId: ObjectId,
      embedding: [Number]
    }]
  }
};

export default PatientProfileSchema;
